import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from './layout.module.css';
import Link from "next/link";// Link機能を使うにはこれが必要です！

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children, 
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        
        {/* --- ここから下がヘッダー要素 --- */}
        <header className={styles.header}>
            クイズ大会
        </header>
        <main>{children}</main>
        {/* ---ここから下がフッター要素--- */}
        <footer className={styles.footer}>
            @zyonetsuaniki
        </footer>

      </body>
    </html>
  );
}